name       : font-util
version    : 1.3.3
release    : 6
source     :
    - https://www.x.org/releases/individual/font/font-util-1.3.3.tar.gz : 2094dd4a1ca63a61deb101d2dc618682d6e287cdbe09679502223ac445d277dc
license    :
    - MIT
    - BSD-2-Clause-NetBSD
    - BSD-2-Clause
    - MIT-open-group
    - Unicode-TOU
component  : xorg.fonts
homepage   : https://xorg.freedesktop.org
summary    : X.Org fonts font-util
description: |
    X.Org font package creation/installation utilities.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
