name       : font-util
version    : 1.3.1
release    : 4
source     :
    - https://www.x.org/releases/individual/font/font-util-1.3.1.tar.gz : 34ebb0c9c14e0a392cdd5ea055c92489ad88d55ae148b2f1cfded0f3f63f2b5b
license    :
    - MIT
component  : xorg.fonts
summary    : |
    X.Org fonts: font-util
description: |
    X.Org fonts: font-util
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
